site_name: jcktch/pckb
site_url: https://mydomain.org/mysite
repo_url: https://github.com/jcktch/pckb.git
repo_name: jcktch/pckb


theme:
  font:
    text: Ubuntu
  name: material
  language: fr
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
  icon:
    logo: fontawesome/solid/terminal
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode sombre

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode clair

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md

  - LABS D'APPRENTISSAGE:
      - Hack The Box:
        - Test: 01_labs_app/htb/machine.md

  - SÉCURITÉ RÉSEAU:
      - TCP/IP:
        - FTP: 02_sec_res/ftp/ftp.md

  - SÉCURITÉ APPLICATIVE:
      - Introduction: 03_sec_app/index.md

  - SÉCURITÉ LINUX:
      - Introduction: 04_sec_lin/index.md

  - SÉCURITÉ WINDOWS:
      - Introduction: 05_sec_win/index.md

  - RÉTRO-INGÉNIERIE:
      - Introduction: 06_ret_ing/index.md

  - CRYPTOGRAPHIE:
      - Introduction: 07_crypto/index.md


      