site_name: jcktch/pckb
site_url: https://mydomain.org/mysite
repo_url: https://github.com/jcktch/pckb.git
repo_name: jcktch/pckb


theme:
  font:
    text: Ubuntu
  name: material
  language: fr
  features:
    - navigation.sections
  icon:
    logo: fontawesome/solid/terminal
  palette:
    - scheme: slate
      primary: yellow
      accent: yellow


extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md

  - LABS D'APPRENTISSAGE:
      - Introduction: laboratoires/index.md

  - SÉCURITÉ RÉSEAU:
      - Introduction: reseau/index.md

  - SÉCURITÉ WINDOWS:
      - Introduction: systemes/index.md

  - SÉCURITÉ LINUX:
      - Introduction: systemes/index.md

  - SÉCURITÉ APPLICATIVE:
      - Introduction: applicatif/index.md

  - RÉTRO-INGÉNIERIE:
      - Introduction: retro-ingenierie/index.md

  - CRYPTOGRAPHIE:
      - Introduction: cryptographie/index.md
